### ISSUE TITLE
在测试test.py时，出现unet_proto.forward() got an unexpected keyword argument 'linear_classifier'。请教一下，十分感谢

### ISSUE THREAD

**Issue by weng-hb** [xjiangmed/LTUDA#1]
Using Unet
/content/LTUDA/code/test.py:44: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  net.load_state_dict(torch.load(args.reload_path))
Traceback (most recent call last):
  File "/content/LTUDA/code/test.py", line 191, in <module>
    test()
  File "/content/LTUDA/code/test.py", line 75, in test
    outputs = net(data_bat, linear_classifier=False, ulp_classifier=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: unet_proto.forward() got an unexpected keyword argument 'linear_classifier'

**Comment by weng-hb** [comment]
大哥，求求了。第一次复现项目

**Comment by xjiangmed** [comment]
Sorry for the late reply. I forgot to update the test code. I will check and re-upload the test code as soon as possible.

**Comment by weng-hb** [comment]
Thank very much for you help! It is very important for my first time to replicate project. Thank you from the bottom of my's heart again.In addition, I would like to ask whether the data set used in train_CDA_PDA.py for the second training is still the same as that used in the first training?The first time model trained with your code worked is very well.Finally, wish you academic success and career success.

**Comment by xjiangmed** [comment]
Yes, the same data set is used for the first and second stages.

**Comment by weng-hb** [comment]
I am all gratitude！

**Comment by LeviAov** [comment]
> I am all gratitude！

你好，请问你复现成功了吗？可以加个联系方式嘛，有偿

**Comment by LeviAov** [comment]
你好，请问你复现成功了吗？可以加个联系方式嘛，有偿

**Comment by LeviAov** [comment]
> I am all gratitude！

你好，请问你复现成功了吗？可以加个联系方式嘛，有偿
